### ISSUE TITLE
Quando viene inserito un file di domande formattato ma senza argomenti la schermata Domande non viene caricata correttamente [BUG]

### ISSUE THREAD

**Issue by FabioC-alt** [mikyll/ROQuiz#17]
**Descrivi il bug**
Quando viene inserito un file con nuove domande, anche se formattato correttamente non viene caricato perchè mancano gli argomenti.

**Come riprodurre**
Passaggi per riprodurre il bug
1. Dalle impostazioni caricare un'altro file di domande.txt
2. Avviare il quiz
3. La schermata resterà bloccata su uno sfondo grigio

**Comportamento previsto**
Dovrebbe aprire il file e riprodurre le domande correttamente

**Comment by mikyll** [comment]
Il bug era causato da una gestione sbagliata delle domande, nel caso non ci fossero argomenti:
Il numero di domande presenti veniva calcolato iterando sugli argomenti, quindi in caso non ce ne fossero, il pool rimaneva a zero.
